"""Stamp a build fingerprint into the package — the artifact's identity card.

Run by CI right before packaging (never by hand for a release):

    python scripts/stamp_build.py

It writes ``src/oaset/_build_info.py`` containing the commit, the build time and
a content fingerprint. The fingerprint is a sha256 over every packaged .py file
plus the commit, so it changes whenever the shipped code changes — even if git
metadata is missing from the build machine. That is the answer to "the version
says 0.10.0 but the behaviour is old": two builds of the same version now have
different fingerprints, and ``oaset --version`` prints the one it is running.

The generated file is not committed (see .gitignore): a tree without it is a
development checkout, and ``runtime_info`` reports it as such.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import subprocess
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PACKAGE = ROOT / "src" / "oaset"
TARGET = PACKAGE / "_build_info.py"


def _git_commit() -> tuple[str, str]:
    def run(*args: str) -> str:
        try:
            out = subprocess.run(["git", *args], cwd=ROOT, capture_output=True,
                                 text=True, check=False, timeout=20)
            return out.stdout.strip() if out.returncode == 0 else ""
        except Exception:
            return ""

    return run("rev-parse", "HEAD"), run("rev-parse", "--abbrev-ref", "HEAD")


def _content_digest() -> str:
    """sha256 over every packaged source file, path-sorted for determinism."""
    digest = hashlib.sha256()
    for path in sorted(PACKAGE.rglob("*.py")):
        if "__pycache__" in path.parts or path.name == "_build_info.py":
            continue
        digest.update(path.relative_to(PACKAGE).as_posix().encode("utf-8"))
        digest.update(b"\0")
        digest.update(hashlib.sha256(path.read_bytes()).digest())
    return digest.hexdigest()


def stamp(*, commit: str | None = None, built_at: str | None = None) -> dict[str, str]:
    """Write _build_info.py and return the info dict (pure enough to test)."""
    from oaset import __version__

    git_commit, branch = _git_commit()
    git_commit = commit or git_commit
    when = built_at or time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())
    digest = _content_digest()
    fingerprint = f"{git_commit[:7] or 'nogit'}-{digest[:12]}"

    body = [
        '"""Generated by scripts/stamp_build.py - do not edit, do not commit."""',
        "",
        f"VERSION = {__version__!r}",
        f"COMMIT = {git_commit!r}",
        f"BRANCH = {branch!r}",
        f"BUILT_AT = {when!r}",
        f"CONTENT_SHA256 = {digest!r}",
        f"FINGERPRINT = {fingerprint!r}",
        "SOURCE = 'frozen'",
        "",
    ]
    TARGET.write_text("\n".join(body), encoding="utf-8")
    return {"version": __version__, "commit": git_commit, "branch": branch,
            "built_at": when, "fingerprint": fingerprint, "content_sha256": digest}


def main() -> int:
    parser = argparse.ArgumentParser(description="stamp a build fingerprint")
    parser.add_argument("--json", action="store_true", help="print the stamp as JSON")
    args = parser.parse_args()
    info = stamp()
    if args.json:
        print(json.dumps(info, ensure_ascii=False, indent=2))
    else:
        print(f"stamped {TARGET.relative_to(ROOT)}")
        print(f"  commit      {info['commit'][:12] or '(none)'} @ {info['branch'] or '-'}")
        print(f"  built_at    {info['built_at']}")
        print(f"  fingerprint {info['fingerprint']}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
